
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'Clarifai' do
pod 'Clarifai', :path => '../'
end

target 'ClarifaiTests' do
pod 'AFNetworking’, ‘~> 3.1’
pod 'Clarifai', :path => '../'
end
